---
# tasks file for nginx_docker
- name: Démarrer le conteneur Nginx
  docker_container:
    name: nginx_container
    image: nginx
    state: started
    ports:
      - "8080:80"
    restart_policy: always
